### PR TITLE
Create unit-test ci.yml

### PR DESCRIPTION
**Pull request by am2089**
# Created a CI script for running Unit test
* Closes issue #53
* Automates the process of running unit tests

# How I Tested
*  Repo can't be tested until it is approved by @mikaelacaron

### CODE REVIEW

**Comment by mikaelacaron** [comment]
@am2089 Do you want to make this a PR to my repo?

**Comment by am2089** [comment]
yes, sorry this is my first time doing this, so im learning along the way.

**Comment by mikaelacaron** [comment]
All good! When you create the PR, you'll see drop downs at the top, you need to make a PR to my repo, as opposed to yours

**Comment by am2089** [comment]
ohhh ok, so should i delete the branch and do it over again?

**Comment by mikaelacaron** [comment]
no need, as long as the branch still exists, which it looks like it does, click the "new pull request" button, and make sure to select my repo in the drop downs

Also look at some GitHub tutorials too, that will help

**Comment by mikaelacaron** [comment]
Screenshot 2023-10-07 at 9 02 17 PM
see here

**Comment by am2089** [comment]
so do I just change the head repo to your repo?

**Comment by mikaelacaron** [comment]
No it should look like this image
`base` is where you wanting to merge the code, the `head` is yours (notice the direction of the arrow)

**Comment by am2089** [comment]
ok, I did it. Thanks for the help!

**Pull request merged**
